<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Quicklight</RootNamespace>
    <StartupObject>Quicklight.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <NoWarn>$(NoWarn);WFAC010</NoWarn>
    <ApplicationIcon>Assets\quicklight.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
    <Using Include="System.IO" />
    <Resource Include="Assets\quicklight.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Quicklight.Core\Quicklight.Core.csproj" />
    <ProjectReference Include="..\Quicklight.Mcp\Quicklight.Mcp.csproj" />
  </ItemGroup>
</Project>
